/* eslint-disable */
// 1. Importamos chromedriver para que macOS no bloquee el test
require('chromedriver');

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test ordenacion colection', function() {
  let driver
  let vars
  
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  
  afterEach(async function() {
    await driver.quit();
  })
  
  it('test ordenacion colection', async function() {
    // 1. Cargar la página
    await driver.get("http://localhost:3000/collection")
    
    // Esperar un poco a que cargue todo inicialmente
    await driver.sleep(2000) 
    
    // 2. Asegurar tamaño de ventana
    await driver.manage().window().setRect({ width: 1102, height: 691 })
    
    // --- TEST: ORDENAR POR PRECIO ---
    
    // 3. Click en el botón "Precio" (El selector generado por IDE)
    // Nota: Este selector .hover... es el botón de Precio según tu grabación
    const precioBtn = await driver.findElement(By.xpath("//button[contains(.,'Precio')]"))
    await precioBtn.click()
    
    // PAUSA CRÍTICA: Esperamos 2 segundos a que React reordene
    console.log("Esperando a que se ordene por precio...")
    await driver.sleep(2000) 

    // 4. Verificar que la primera carta es Charizard
    const textoCarta1 = await driver.findElement(By.css(".relative:nth-child(1) .text-sm")).getText()
    console.log("Primera carta encontrada:", textoCarta1)
    assert(textoCarta1 == "Charizard Base Set")
    
    
    // --- TEST: ORDENAR POR NOMBRE ---

    // 5. Click en el botón "Nombre"
    const nombreBtn = await driver.findElement(By.xpath("//button[contains(.,'Nombre')]"))
    await nombreBtn.click()
    
    // PAUSA CRÍTICA: Esperamos 2 segundos a que React reordene
    console.log("Esperando a que se ordene por nombre...")
    await driver.sleep(2000)

    // 6. Verificar que la primera carta es Alakazam
    const textoCarta2 = await driver.findElement(By.css(".relative:nth-child(1) .text-sm")).getText()
    console.log("Primera carta encontrada:", textoCarta2)
    assert(textoCarta2 == "Alakazam Base Set")
  })
})

// se han tenido que añadir esperas manuales (driver.sleep) para que React tenga 
// tiempo de reordenar las cartas antes de hacer las comprobaciones.